id: kubernetes-mirantis

info:
  name: Mirantis Kubernetes Engine Panel - Detect
  author: pussycat0x
  severity: info
  description: Mirantis Kubernetes Engine panel was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:mirantis:kubernetes_engine:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: mirantis
    product: kubernetes_engine
    shodan-query: http.html:"mirantis kubernetes engine"
    fofa-query:
      - app="mirantis-kubernetes-engine"
      - body="mirantis kubernetes engine"
    runzero-match: service["http.body"] matches "(?i)Mirantis Kubernetes Engine"
  tags: tech,kubernetes,devops,kube,k8s,panel

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Mirantis Kubernetes Engine"

      - type: status
        status:
          - 200

