id: amp-application-panel

info:
  name: Application Management Panel - Detect
  author: DhiyaneshDK
  severity: info
  description: Application Management Panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cubecoders:amp:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: cubecoders
    product: amp
    shodan-query: http.title:"amp - application management panel"
    fofa-query: title="amp - application management panel"
    google-query: intitle:"amp - application management panel"
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)amp - application management panel"})
  tags: panel,amp,cubecoders

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>AMP - Application Management Panel</title>"

      - type: word
        part: header
        words:
          - "text/html"

