id: composer-auth-json

info:
  name: Composer-auth Json File Disclosure
  author: DhiyaneshDK
  severity: low
  description: Composer Auth Josn file is disclosed.
  reference: https://www.exploit-db.com/ghdb/5768
  classification:
    cpe: cpe:2.3:a:getcomposer:composer:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: getcomposer
    product: composer
    google-query: intext:"index of /" ".composer-auth.json"
  tags: exposure,devops,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.composer-auth.json"
      - "{{BaseURL}}/vendor/webmozart/assert/.composer-auth.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'github-oauth'
          - 'github.com'
        condition: and

      - type: status
        status:
          - 200

