id: confluence-installer

info:
  name: Confluence Installation Page - Exposure
  author: DhiyaneshDK
  severity: high
  description: |
    Confluence is susceptible to the Installation page exposure due to misconfiguration.
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Choose your deployment type - Confluence"
  tags: misconfig,exposure,install,confluence

http:
  - method: GET
    path:
      - "{{BaseURL}}/setup/setupcluster-start.action"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Choose your deployment type - Confluence"

      - type: status
        status:
          - 200

