id: default-credentials-config-files
info:
  name: Default Credentials Detection in Configuration Files
  author: Kaan
  severity: critical
  description: Detects usage of default credentials in configuration files
  tags: config, credentials, security
file:
- extensions:
  - yaml
  - json
  - conf
  matchers:
  - type: regex
    regex:
    - username:\s*admin
    - password:\s*admin
    - password:\s*123456
  extractors:
  - type: regex
    regex:
    - username:\s*admin
    - password:\s*admin
    - password:\s*123456
