id: firebase-config-exposure

info:
  name: Detection Firebase Config
  author: Shir0E
  severity: low
  tags: firebase, exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "firebaseapp.com"
          - "appspot.com"
          - "firebaseConfig"