id: gunicorn-config-file

info:
  name: Gunicorn Config File - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Gunicorn Config file is exposed.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"gunicorn.conf.py"
  tags: exposure,files,gunicorn

http:
  - method: GET
    path:
      - '{{BaseURL}}/gunicorn.conf.py'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'bind ='
          - 'workers ='
        condition: and
        case-insensitive: true

      - type: word
        part: content_type
        words:
          - 'text/x-python'

