id: haproxy-config-file

info:
  name: Haproxy Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Haproxy Config file is exposed.
  reference:
    - https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"haproxy.cfg"
  tags: exposure,files,haproxy

http:
  - method: GET
    path:
      - '{{BaseURL}}/haproxy.cfg'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '/var/run/haproxy.pid'
          - 'pidfile'
        condition: and
        case-insensitive: true

      - type: word
        part: content_type
        words:
          - 'text/plain'

