id: hardcoded-secrets-config-files
info:
  name: Hardcoded Secrets in Configuration Files Detection
  author: Kaan
  severity: critical
  description: Detects hardcoded secrets in common configuration files like .env,
    .conf, .properties
  tags: config, secrets, sensitive-data
file:
- extensions:
  - env
  - conf
  - properties
  matchers:
  - type: regex
    regex:
    - password=.*
    - secret=.*
    - token=.*
  extractors:
  - type: regex
    regex:
    - password=.*
    - secret=.*
    - token=.*
