id: icecast-config

info:
  name: Icecast Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Icecast Config file is exposed.
  reference:
    - https://icecast.org/docs/icecast-trunk/config_file/
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="icecast.xml"
  tags: exposure,icecast,config,files

http:
  - method: GET
    path:
      - '{{BaseURL}}/icecast.xml'

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(content_type, "application/xml")'
          - 'contains_all(body, "<hostname>","<fileserve>")'
        condition: and

