id: mobile-insecure-webview-config
info:
  name: Insecure WebView Configuration Detection
  author: Kaan
  severity: high
  description: Detects insecure WebView configurations in mobile applications
  tags: java, mobile, webview
file:
- extensions:
  - java
  matchers:
  - type: regex
    regex:
    - setJavaScriptEnabled\s*\(\s*true\)
    - setAllowFileAccess\s*\(\s*true\)
  extractors:
  - type: regex
    regex:
    - setJavaScriptEnabled\s*\(\s*true\)
    - setAllowFileAccess\s*\(\s*true\)
