id: mobile-android-debuggable-config
info:
  name: Insecure Android Debuggable Configuration Detection
  author: Kaan
  severity: high
  description: Detects if an application is set to debuggable in AndroidManifest.xml
  tags: mobile, androidmanifest, debuggable
file:
- extensions:
  - xml
  matchers:
  - type: regex
    regex:
    - <application[^>]*android:debuggable=['"]true['"]
  extractors:
  - type: regex
    regex:
    - <application[^>]*android:debuggable=['"]true['"]
