id: nuxtjs-config-file

info:
  name: Nuxtjs Config File - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Nuxtjs Config file is exposed.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"nuxt.config.ts"
  tags: exposure,files,nuxtjs

http:
  - method: GET
    path:
      - '{{BaseURL}}/nuxt.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'export default {'
          - 'buildModules: ['
        condition: and
        case-insensitive: true

      - type: word
        part: content_type
        words:
          - 'application/javascript'

