id: password-policy-expiration-unconfigured

info:
  name: RAM Password Policy Expiration - Unconfigured
  author: DhiyaneshDK
  severity: medium
  description: |
    The Alibaba Cloud RAM Password Policy is unconfigured, leaving user accounts vulnerable to weak or expired passwords. This lack of a configured policy may lead to potential unauthorized access due to weak password management.
  reference:
    - https://www.alibabacloud.com/help/en/ram/user-guide/configure-a-password-policy-for-ram-users
    - https://www.trendmicro.com/cloudoneconformity/knowledge-base/alibaba-cloud/AlibabaCloud-RAM/require-password-expiration-policy.html
  metadata:
    max-request: 1
    verified: true
  tags: cloud,devops,aliyun,alibaba,alibaba-cloud-config,alibaba-ram

variables:
  region: "cn-hangzhou"

self-contained: true

code:
  - engine:
      - sh
      - bash

    source: |
      aliyun ram GetPasswordPolicy --region $region

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - '"MaxPasswordAge":\s*(9[1-9]|[1-9][0-9]{2,})'  # Matches values greater than 90

      - type: regex
        regex:
          - '"MaxPasswordAge":\s*(0|[1-9][0-9]?)'  # Excludes values between 0 and 90

    extractors:
      - type: dsl
        dsl:
          - '"RAM Password Policy Expiration is Greater than 90 Days "'

