id: saltstack-config-panel

info:
  name: SaltStack Config Panel - Detect
  author: pussycat0x
  severity: info
  description: |
    SaltStack config panel was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:saltstack:saltstack:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: saltstack
    product: saltstack
    shodan-query: http.title:"saltstack config"
    fofa-query: title="saltstack config"
    google-query: intitle:"saltstack config"
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)SaltStack Config"})
  tags: panel,vmware,login,saltstack

http:
  - method: GET
    path:
      - "{{BaseURL}}/login"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "SaltStack Config"

      - type: status
        status:
          - 200

