id: yahoo-site-db-config

info:
  name: Find Exposing of yahoo_site_admin/credentials/db.conf
  author: Shiroe
  severity: high
  metadata:
    google-dork: inurl:"yahoo_site_admin/credentials/db.conf"
  tags: exposure

requests:
  - method: GET
    path:
      - "{{RootURL}}/yahoo_site_admin/credentials/db.conf"
    
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<dbcredentials"