id: mobile-websocket-insecure-config
info:
  name: Insecure WebSocket Configuration Detection
  author: Kaan
  severity: critical
  description: Detects insecure WebSocket connections in mobile applications
  tags: java, mobile, websocket
file:
- extensions:
  - java
  matchers:
  - type: regex
    regex:
    - new\s+WebSocket\s*\(\s*['"]ws://.*['"]\)
    - client\.connect\s*\(\s*.*['"]ws://.*['"]\)
  extractors:
  - type: regex
    regex:
    - new\s+WebSocket\s*\(\s*['"]ws://.*['"]\)
    - client\.connect\s*\(\s*.*['"]ws://.*['"]\)
