id: prometheus-unauth

info:
  name: Prometheus Monitoring System - Unauthenticated
  author: pussycat0x
  severity: high
  description: |
    Detects unauthenticated access to Prometheus Time Series Collection and Processing Server by checking for specific elements in the response from the `/graph` endpoint.
  metadata:
    verified: true
    max-request: 2
    shodan-query: http.title:"Prometheus Time Series"
  tags: unauth,prometheus,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/config"
      - "{{BaseURL}}/api/v1/status/config"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "global:"
          - "scrape_configs:"
          - "scrape_interval"
        condition: and

      - type: status
        status:
          - 200

