id: slack-config-refresh-token

info:
  name: Slack Config Refresh Token
  author: DhiyaneshDK
  severity: info
  reference:
    - https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/gitleaks/slack-config-refresh-token.txt
    - https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/gitleaks/slack-config-refresh-token.yaml
    - https://api.slack.com/authentication
  metadata:
    max-request: 1
  tags: exposure,token,slack

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - (?i)(xoxe-\d-[A-Z0-9]{146})

