id: java-cors-misconfiguration
info:
  name: Java CORS Misconfiguration Detection
  author: kaanbicaklar
  severity: high
  description: Detects insecure CORS configurations in Java applications
  tags: java, cors, security
file:
- extensions:
  - java
  matchers:
  - type: regex
    regex:
    - setHeader\s*\(\s*['"]Access-Control-Allow-Origin['"],\s*['"].*['"]\)
    - cors\.setAllowedOrigins\s*\(\s*['"].*['"]\)
  extractors:
  - type: regex
    regex:
    - setHeader\s*\(\s*['"]Access-Control-Allow-Origin['"],\s*['"].*['"]\)
    - cors\.setAllowedOrigins\s*\(\s*['"].*['"]\)
