id: django-debug-config-enabled

info:
  name: Django Debug Configuration Enabled
  author: dhiyaneshDK,hackergautam
  severity: medium
  description: Django debug configuration is enabled, which allows an attacker to obtain system configuration information such as paths or settings.
  metadata:
    max-request: 1
  tags: django,debug,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}/NON_EXISTING_PATH/"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - URLconf defined
          - Page not found
          - Django tried these URL patterns, in this order
        condition: and

      - type: status
        status:
          - 404

