id: 3cx-config

info:
  name: 3CX Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    3CX Configuration file was discovered.
  reference:
    - https://www.3cx.com/docs/configure-pbx-automatically/
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"setupconfig.xml"
  tags: 3cx,config,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/SetupConfig.xml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "3CX"
          - "<SetupConfig"
        condition: and

      - type: word
        part: content_type
        words:
          - "application/xml"

