id: nconf-panel

info:
  name: NConf Login Panel - Detect
  author: ritikchaddha
  severity: info
  description: NConf login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:nconf_project:nconf:*:*:*:*:node.js:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: nconf_project
    product: nconf
    shodan-query: http.title:"nconf"
    fofa-query: title="nconf"
    google-query: intitle:"nconf"
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)nconf"})
  tags: panel,nconf

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "nconf.js"
          - "<title>NConf"
        condition: or

      - type: status
        status:
          - 200

