id: neo4j-neodash-config

info:
  name: Neo4j Neodash Config - Exposure
  author: icarot
  severity: medium
  description: |
    Detects the file config.json from Neo4j Neodash web application, it contains information about DB connection with Neo4J.
  classification:
    cpe: cpe:2.3:a:neo4j:*:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: neo4j
    product: neodash
    shodan-query: title:"NeoDash"
  tags: config,exposure,neodash,neo4j

http:
  - method: GET
    path:
      - "{{BaseURL}}/config.json"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'standaloneHost'
          - 'standalonePort'
          - 'standaloneDatabase'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200

    extractors:
      - type: json
        name: config
        part: body
        json:
          - '.standaloneDatabase,.standaloneUsername,.standalonePassword'

