id: neon-db-config

info:
  name: Find Exposing of app/config/config.local.neon
  author: Shiroe
  severity: medium
  tags: exposure

requests:
  - method: GET
    path:
      - "{{RootURL}}/app/config/config.local.neon"
    
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "database"