id: vite-config

info:
  name: Vite Configuration - File Exposure
  author: DhiyaneshDk
  severity: low
  description: |
    The vite.config.js file is used to customize the behavior of Vite and specify various settings for your project.
  reference:
    - https://vitejs.dev/config/
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"vite.config.js"
  tags: devops,exposure,files,vite,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/vite.config.js"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'export default defineConfig'
          - 'plugins:'
          - 'laravel'
        condition: and

      - type: status
        status:
          - 200

