id: rconfig-default-login

info:
  name: rConfig - Default Login
  author: theamanrawat
  severity: high
  description: |
    rConfig default login credentials were discovered.
  reference:
    - https://github.com/rconfig/rconfig
  classification:
    cpe: cpe:2.3:a:rconfig:rconfig:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: rconfig
    product: rconfig
    shodan-query: http.title:"rconfig"
    fofa-query: title="rconfig"
    google-query: intitle:"rconfig"
    runzero-match: any(each(service["html.titles"]), {# matches "rConfig"})
  tags: rconfig,default-login

http:
  - raw:
      - |
        GET /login.php HTTP/1.1
        Host: {{Hostname}}
      - |
        POST /lib/crud/userprocess.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        user={{username}}&pass={{password}}&sublogin=1

    attack: pitchfork
    payloads:
      username:
        - "admin"
      password:
        - "admin"
    host-redirects: true

    matchers-condition: and
    matchers:
      - type: word
        part: body_2
        words:
          - "Logged in as"
          - "rConfig - Configuration Management"
          - "dashboadFieldSet"
        condition: and

      - type: word
        part: header_2
        words:
          - text/html

      - type: status
        part: header_2
        status:
          - 200

