id: next-js-config-file

info:
  name: Next JS Config - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Next JS Config file is exposed.
  reference:
    - https://nextjs.org/docs/app/api-reference/config/next-config-js
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"next.config.js"
  tags: exposure,files,nextjs

http:
  - method: GET
    path:
      - '{{BaseURL}}/next.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'nextConfig'
          - 'module.exports ='
        condition: and
        case-insensitive: true

      - type: status
        status:
          - 200

