id: lighttpd-config-file

info:
  name: Lighttpd Config File - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Lighttpd Config file is exposed.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"lighttpd.conf"
  tags: exposure,files,lighttpd

http:
  - method: GET
    path:
      - '{{BaseURL}}/lighttpd.conf'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'server.document-root ='
          - 'server.port ='
        condition: and
        case-insensitive: true

      - type: word
        part: content_type
        words:
          - 'application/octet-stream'

