id: esphome-panel

info:
  name: ESPHome Login Panel - Detect
  author: fabaff
  severity: info
  description: ESPHome login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:esphome:esphome:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: esphome
    product: esphome
    shodan-query:
      - http.title:"login - esphome"
      - http.title:"dashboard - esphome"
    fofa-query:
      - title="login - esphome"
      - title="dashboard - esphome"
    google-query:
      - intitle:"login - esphome"
      - intitle:"dashboard - esphome"
    runzero-match: any(each(service["html.titles"]), {# matches "(?i)login - esphome"})
  tags: panel,esphome,iot

http:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'class="esphome-header'

      - type: status
        status:
          - 200

