id: java-improper-http-header-security
info:
  name: Java Improper HTTP Header Security Detection
  author: kaanbicaklar
  severity: high
  description: Detects missing or insecure HTTP header settings in Java web applications
  tags: java, http, headers
file:
- extensions:
  - java
  matchers:
  - type: regex
    regex:
    - response\.setHeader\s*\(\s*['"]X-Content-Type-Options['"],\s*['"].*['"]\)
    - response\.setHeader\s*\(\s*['"]X-Frame-Options['"],\s*['"].*['"]\)
  extractors:
  - type: regex
    regex:
    - response\.setHeader\s*\(\s*['"]X-Content-Type-Options['"],\s*['"].*['"]\)
    - response\.setHeader\s*\(\s*['"]X-Frame-Options['"],\s*['"].*['"]\)
